# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
map f11 toggle_fullscreen
clipboard_control write-primary

#Tab bar
tab_bar_min_tabs            1
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
#Ends Tab bar

#Tab bar 2
#tab_bar_edge bottom
#tab_bar_align left
#tab_bar_style custom
#tab_bar_min_tabs 1
#tab_activity_symbol none
#bell_on_tab no
#tab_separator ""
#tab_bar_margin_width 0.0
#tab_bar_margin_height 0.0 0.0
#tab_title_template "{f'{title[:30]}…' if title.rindex(title[-1]) + 1 > 30 else (title.center(6) if (title.rindex(title[-1]) + 1) % 2 == 0 else title.center(5))}"
#active_tab_font_style   bold

#Font
font_family JetBrains Mono Nerd Font
font_size 14.0
bold_font auto
italic_font auto
bold_italic_font auto

#To remove the top bar
linux_display_server x11

#Window decoration
hide_window_decorations no

# ----- window settings ----- #

 remember_window_size      yes
# initial_window_width      640
# initial_window_height     400

#window_padding_width        12 24 0 24
#placement_strategy          center
#resize_in_steps             yes
#hide_window_decorations     titlebar-only
#background_opacity          0.9
#inactive_text_alpha         1.0
#enabled_layouts             splits, stack

